name: Squid Proxy with Cloudflared

on: [push, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies (Squid, Cloudflared)
      run: |
        sudo apt update
        sudo apt install -y squid wget curl nodejs npm

    - name: Configure Squid Proxy for HTTPS
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        http_access allow all
        cache deny all
        access_log none
        EOF

    - name: Start Squid Proxy
      run: |
        sudo systemctl restart squid
        sudo systemctl enable squid

    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Start Cloudflared Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:3128 > cloudflared.log 2>&1 &
        sleep 5
        cat cloudflared.log | grep -o 'https://.*\.trycloudflare.com' || echo "Tunnel failed"

    - name: Keep Alive (for testing)
      run: sleep 3600
