name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install Python & cloudflared
      run: |
        sudo apt update
        sudo apt install -y python3-pip wget curl
        pip install --upgrade proxy.py

        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb
        sudo dpkg -i cloudflared.deb

    - name: Start proxy.py server
      run: |
        nohup proxy --hostname 127.0.0.1 --port 8080 > proxy.log 2>&1 &

    - name: Start Cloudflare Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:8080 > cloudflared.log 2>&1 &

    - name: Wait and Show Tunnel URL
      run: |
        sleep 10
        echo "========================"
        echo "Proxy server is running"
        echo "Tunnel URL (check below):"
        tail -n 20 cloudflared.log | grep 'trycloudflare.com'
        echo "========================"

    - name: Keep job alive for 1 hour
      run: sleep 3600
