name: Expose SOCKS5 Proxy via Cloudflared


on: [push, workflow_dispatch]

jobs:
  frp-cloudflare:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Install Dante SOCKS5 proxy
      run: |
        sudo apt update
        sudo apt install -y dante-server
        cat <<EOF | sudo tee /etc/danted.conf
        logoutput: /var/log/danted.log
        internal: 0.0.0.0 port = 1080
        external: eth0
        method: username none
        user.notprivileged: nobody
        client pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
            log: connect disconnect error
        }
        pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
            protocol: tcp udp
            log: connect disconnect error
        }
        EOF
        sudo systemctl restart danted
  
    - name: Download and run cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared
        ./cloudflared tunnel --url socks5://localhost:1080 &
        sleep 10
        curl -s http://127.0.0.1:4040/quicktunnel | tee result.json
  
    - name: Show tunnel URL
      run: |
        echo "Tunnel URL:"
        cat result.json
