name: Cloudflare + FRP Proxy

on: [push, workflow_dispatch]

jobs:
  frp-cloudflare:
    runs-on: ubuntu-latest

    steps:
    - name: Install Proxy (Dante for SOCKS5)
      run: |
        sudo apt update
        sudo apt install -y dante-server
        cat <<EOF | sudo tee /etc/danted.conf
        logoutput: stderr
        internal: 127.0.0.1 port = 1080
        external: $(hostname -I | awk '{print $1}')
        method: none
        user.notprivileged: nobody
        client pass {
          from: 0.0.0.0/0 to: 0.0.0.0/0
          log: error
        }
        pass {
          from: 0.0.0.0/0 to: 0.0.0.0/0
          log: error
          protocol: tcp udp
          method: none
        }
        EOF
        sudo danted -f /etc/danted.conf &

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

    - name: Run Cloudflared Tunnel
      run: |
        sudo cloudflared service install eyJhIjoiYWM2NDc1NzkyZTJkNjY3ODc4M2JmMTFhOGI5MTFiYzciLCJ0IjoiZGM4MDBkZTktNjA0YS00NzUzLWIwZTgtYzIzZjViMmM3ZjM2IiwicyI6IllqQTBOelU1TlRJdFlqRTJNQzAwWXpJNExXRTBPRGd0T1RFek9UQTJaRFk0TURGaiJ9
        nohup cloudflared tunnel --url http://localhost:1080 > tunnel.log 2>&1 &
        sleep 10
        tail -n 20 tunnel.log

    - name: Keep job alive
      run: sleep 3600
