name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo apt-get install android-tools-adb
    - run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo docker run -itd --rm --privileged --pull always -v ~/data:/data -p 5555:5555 redroid/redroid:11.0.0-latest

    - run: sleep 10
    - run: adb connect 127.0.0.1:5555
    - run: sleep 1
    - run: adb devices
    
    - name: Node Js
      run: wget https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/test.js https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/package.json
    - run: npm install form-data adbkit axios fs
    - run: node test.js 
