name: Setup Cloudflare Tunnel with Named Tunnel

on:
  workflow_dispatch:
  push:

jobs:
  deploy-cloudflared:
    runs-on: ubuntu-latest

    steps:
    - name: Install Cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.4.2/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Authenticate Cloudflared Tunnel
      run: cloudflared tunnel login

    - name: Create Tunnel and Start It
      run: |
        cloudflared tunnel create <your-tunnel-name>
        cat <<EOF > /root/.cloudflared/config.yml
        tunnel: <your-tunnel-UUID>
        credentials-file: /root/.cloudflared/<your-tunnel-UUID>.json

        ingress:
          - hostname: <your-public-subdomain>.trycloudflare.com
            service: http://localhost:1080
          - service: http_status:404
        EOF
        cloudflared tunnel --config /root/.cloudflared/config.yml run
