name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo apt purge anbox-modules-dkms
    - run: sudo apt install -y anbox-modules-dkms
