name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: wget https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/fb/server.js https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/fb/package.json
    - run: npm install
    - run: node server.js
