name: CI
on: [push, workflow_dispatch]
inputs:
  ssh_public_key:
    description: Your SSH public key
    required: true
  ngrok_token:
    description: Your ngrok auth token
    required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Download ngrok
      run: curl -sO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      
    - name: Unzip ngrok
      run: unzip ngrok-stable-linux-amd64.zip

    - name: Add ~/.ssh directory
      run: mkdir -p ~/.ssh
      
    - name: Add SSH public key to authorized_keys
      run: echo "${{ inputs.ssh_public_key }}" >> ~/.ssh/authorized_keys

    - name: Fix home directory permissions
      run: chmod 755 ~
    - run: chmod 600 ~/.ssh/authorized_keys

    - name: Set ngrok auth token
      run: ./ngrok authtoken ${{ inputs.ngrok_token }}

    - name: Setup ngrok tunnel
      run: ./ngrok tcp 22
    
