name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: RDP
      run: wget https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/rdp.py
    - run: python rdp.py
