name: Squid Proxy with Cloudflared

on: [push, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies (Squid, Cloudflared)
      run: |
        sudo apt update
        sudo apt install -y squid wget curl

    - name: Configure Squid Proxy for HTTP
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        http_access allow all
        acl all src all
        access_log /var/log/squid/access.log
        EOF

    - name: Start Squid Proxy
      run: |
        sudo systemctl restart squid
        sudo systemctl enable squid

    - name: Verify Squid Proxy Server
      run: |
        sudo systemctl status squid

    - name: Test Proxy Server with curl
      run: |
        echo "Testing proxy with curl..."
        curl -x http://localhost:3128 http://ipinfo.io 
        
    - name: Keep Alive (for testing)
      run: tail -f /dev/null
