name: Squid Proxy with LocalTunnel

on: [push, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Squid Proxy
      run: |
        sudo apt update
        sudo apt install -y squid nodejs npm

    - name: Configure Squid for basic HTTPS proxy
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        http_access allow all
        cache deny all
        access_log none
        EOF

    - name: Start Squid
      run: |
        sudo systemctl restart squid
        sudo systemctl enable squid

    - name: Install LocalTunnel
      run: |
        npm install -g localtunnel

    - name: Start LocalTunnel for Squid (port 3128)
      run: |
        lt --port 3128 > squid_tunnel.log 2>&1 &
        sleep 5
        cat squid_tunnel.log | grep -o 'https://.*\.loca\.lt' || echo "Tunnel failed"

    - name: Keep Alive
      run: sleep 3600
