name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo apt-get install android-tools-adb
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Dockerfile
    - run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/system.tar
    - run: sudo docker build . -t redroid:11.0.0-nb
    - run: sudo docker run -itd --rm --privileged -v ~/data11-nb:/data -p 5555:5555 --name emulator redroid:11.0.0-nb
    - run: sleep 5
    - run: sudo docker exec -it emulator chmod 777 /system/bin/su
    - run: sudo docker exec -it emulator chmod 777 /system/bin/supolicy
    - run: sudo docker exec -it emulator chmod 777 /system/bin/chattr
    - run: sudo docker exec -it emulator chmod 777 /system/bin/chattr.pie
    - run: sudo docker exec -it emulator chmod 777 /system/bin/libsupol.so
    
    - name: Adb
      run: adb connect 127.0.0.1:5555
    - run: adb devices
    - run: sleep 3
    - run: adb -s 127.0.0.1:5555 shell ls -l /system/xbin/
    - run: adb -s 127.0.0.1:5555 shell "su -c getprop ro.product.cpu.abi"

    - name: Node Js
      run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/adb https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/test.js https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/package.json https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/FbCreator.apk
    - run: npm install form-data axios fs
    - run: sudo chmod 777 adb
    - run: node test.js
