name: Squid HTTP Proxy Server Setup

on: [push, workflow_dispatch]

jobs:
  setup-squid-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Update and Install Squid
        run: |
          sudo apt update
          sudo apt install -y squid

      - name: Configure Squid Proxy Server
        run: |
          # Backup the original squid.conf file
          sudo cp /etc/squid/squid.conf /etc/squid/squid.conf.bak

          # Configure Squid to listen on port 3128 (one line configuration)
          sudo bash -c 'echo "http_port 3128\nhttp_access allow all\ncache_mem 64 MB\nmaximum_object_size_in_memory 8 KB\nmaximum_object_size 100 MB\ncache_dir ufs /var/spool/squid 100 16 256" > /etc/squid/squid.conf'

      - name: Start Squid Proxy Server
        run: |
          sudo systemctl restart squid
          sudo systemctl enable squid

      - name: Verify Squid Proxy Server
        run: |
          # Verify Squid is running
          sudo systemctl status squid

      - name: Test Proxy Server with curl
        run: |
          # Test the proxy server by sending a request via curl
          echo "Testing proxy with curl..."
          curl -x http://localhost:3128 http://ipinfo.io
