name: Cloudflare Tunnel Proxy Setup

on:
  push:
    branches:
      - main  # অথবা আপনার প্রেফারড ব্রাঞ্চ

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl unzip
        pip install proxy.py
        
    - name: Install Cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb
        sudo dpkg -i cloudflared.deb
        
    - name: Run proxy.py as HTTP Proxy
      run: |
        nohup proxy --hostname 127.0.0.1 --port 8080 > proxy.log 2>&1 &  # Start proxy.py on localhost:8080
        
    - name: Start Cloudflare Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:8080 > cloudflared.log 2>&1 &  # Expose proxy.py via Cloudflare Tunnel
        
    - name: Wait for tunnel to start
      run: sleep 10  # Wait for tunnel to initialize (adjust timing if needed)

    - name: Test Proxy with curl
      run: |
        curl -x http://localhost:8080 https://ipinfo.io  # Test if the proxy works
    
    - name: Check proxy output
      run: |
        tail -n 10 proxy.log  # Print last 10 lines of proxy.py log to confirm it's working
