name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo dkms install anbox-modules-ashmem/r1213.c898810 -k 5.7.2-arch1-1
