name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo docker run -d -p 5555:5555 -e EMULATOR_DEVICE="Samsung Galaxy S10" --device /dev/kvm --name emulator budtmo/docker-android:emulator_11.0

    - name: Node Js
      run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/adb https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/server.js https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/package.json https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Caarlos.apk
    - run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Facebook.apk https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Lite.apk https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/FbVirtual.apk https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/FbCreator.apk
    - run: npm install fs
    - run: sudo chmod 777 adb
    - run: node server.js
