name: Dante SOCKS5 with FRP and Cloudflared

on: [push, workflow_dispatch]

jobs:
  setup-socks5-frp:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dante SOCKS5
        run: |
          sudo apt update
          sudo apt install -y dante-server
          cat <<EOF | sudo tee /etc/danted.conf
          logoutput: /var/log/danted.log
          internal: 0.0.0.0 port = 1080
          external: eth0
          method: username none
          user.notprivileged: nobody
          client pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
            log: connect disconnect error
          }
          pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
            protocol: tcp udp
            log: connect disconnect error
          }
          EOF
          sudo systemctl restart danted
          sudo systemctl enable danted

      - name: Download and Install FRP
        run: |
          wget https://github.com/fatedier/frp/releases/download/v0.45.0/frp_0.45.0_linux_amd64.tar.gz
          tar -xvf frp_0.45.0_linux_amd64.tar.gz
          cd frp_0.45.0_linux_amd64
          sudo mv frpc /usr/local/bin/
          sudo mv frps /usr/local/bin/

      - name: Start FRP Client
        run: |
          nohup frpc -c <path_to_your_frpc_config_file> > frpc.log 2>&1 &
        
      - name: Install Cloudflared
        run: |
          wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Start Cloudflared Tunnel
        run: |
          nohup cloudflared tunnel --url http://localhost:1080 > tunnel.log 2>&1 &
        
      - name: Wait for Tunnel URL
        run: |
          echo "Waiting for Cloudflared tunnel..."
          for i in {1..30}; do
            if grep -o 'https://.*\.trycloudflare\.com' tunnel.log; then
              grep -o 'https://.*\.trycloudflare\.com' tunnel.log > url.txt
              break
            fi
            sleep 2
          done
          echo "Tunnel URL:"
          cat url.txt

      - name: Keep Action Alive
        run: |
          echo "Tunnel running. Sleeping forever..."
          tail -f /dev/null
