name: Squid Proxy with Cloudflared

on: [push, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies (Squid, Cloudflared)
      run: |
        sudo apt update
        sudo apt install -y squid wget curl

    - name: Configure Squid Proxy for HTTP
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        http_access allow all
        acl all src all
        access_log /var/log/squid/access.log
        EOF

    - name: Start Squid Proxy
      run: |
        sudo systemctl restart squid
        sudo systemctl enable squid

    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Start Cloudflared Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost:3128 > cloudflared.log 2>&1 &
        sleep 10
        grep -o 'https://.*\.trycloudflare\.com' cloudflared.log > proxy_url.txt || echo "Tunnel failed"
        cat proxy_url.txt

    - name: Test Proxy with curl
      run: |
        PROXY_URL=$(cat proxy_url.txt | sed 's/https:/http:/')
        echo "Testing proxy via $PROXY_URL"
        curl -x $PROXY_URL http://ipinfo.io

    - name: Keep Alive (for testing)
      run: tail -f /dev/null
