name: HTTPS Proxy via Dante
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dante Proxy (HTTP)
      run: |
        sudo apt update
        sudo apt install -y dante-server curl jq

    - name: Configure Dante Proxy (HTTP)
      run: |
        sudo tee /etc/danted.conf > /dev/null <<EOF
        logoutput: /var/log/dante.log
        internal: eth0 port = 3128
        external: eth0
        method: username none
        user.notprivileged: nobody
        clientmethod: none
        socksmethod: none
        http_port 3128
        EOF

    - name: Start Dante Proxy
      run: sudo systemctl restart danted

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install -y ngrok

    - name: Set Ngrok Authtoken
      run: ngrok config add-authtoken 2YMpPG6ws3Y1x5unwwSlUNVs3Wu_67JPAFd2MmxAo7cBVK7Lq

    - name: Start Ngrok HTTP Tunnel
      run: nohup ngrok http 3128 > /tmp/ngrok.log 2>&1 &

    - name: Wait and Show Ngrok URL
      run: |
        sleep 8
        curl -s http://localhost:4040/api/tunnels > tunnels.json
        proxy_url=$(grep -oE 'http://[^"]+' tunnels.json)
        echo "HTTP Proxy URL: $proxy_url"

    - name: Keep Alive
      run: tail -f /dev/null
      
