name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo dkms add -m anbox-binder -v 1
    - run: sudo dkms build -m anbox-binder -v 1
    - run: sudo dkms install -m anbox-binder -v 1
    - run: sudo modprobe ashmem-linux binder-linux
