name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: RDP
      run: wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
    - run: sudo dpkg --install chrome-remote-desktop_current_amd64.deb
    - run: sudo apt install --assume-yes --fix-broken
