name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: docker run -itd --rm --privileged -v ~/data11-nb:/data -p 5555:5555 --name emulator redroid/redroid:11.0.0-latest
    - run: docker exec -it emulator ls -l

