name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip wget curl unzip
          pip3 install proxy.py

      - name: Start local HTTPS proxy
        run: |
          nohup proxy --hostname 0.0.0.0 --port 8080 > proxy.log 2>&1 &

      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflare Tunnel
        run: |
          nohup cloudflared tunnel --url http://localhost:8080 > tunnel.log 2>&1 &
          sleep 10
          echo "=== Tunnel Log ==="
          cat tunnel.log

      - name: Keep alive
        run: sleep 3600
