name: Squid Proxy with Cloudflared

on: [push, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest

    name: Squid Proxy with Cloudflared Named Tunnel

    steps:
    - name: Install Dependencies (Squid, Cloudflared)
      run: |
        sudo apt update
        sudo apt install -y squid wget curl
    
    - name: Configure Squid
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        http_access allow all
        acl all src all
        access_log /var/log/squid/access.log
        EOF
    
        sudo systemctl restart squid
        sudo systemctl enable squid
    
    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/
    
    - name: Authenticate Named Tunnel
      env:
        TUNNEL_TOKEN: ${{ secrets.CLOUDFLARED_TUNNEL_TOKEN }}
      run: |
        echo "$TUNNEL_TOKEN" | sudo cloudflared service install
    
    - name: Create config.yml for Named Tunnel
      run: |
        sudo mkdir -p /etc/cloudflared
        cat <<EOF | sudo tee /etc/cloudflared/config.yml
        tunnel: $(basename /etc/cloudflared/*.json .json)
        credentials-file: /etc/cloudflared/$(basename /etc/cloudflared/*.json)
    
        ingress:
          - hostname: proxy.raiyan086.xyz
            service: http://localhost:3128
          - service: http_status:404
        EOF
    
    - name: Start cloudflared service
      run: |
        sudo systemctl enable cloudflared
        sudo systemctl start cloudflared
        sleep 5
    
    - name: Test Proxy with curl
      run: |
        curl -x http://proxy.raiyan086.xyz http://ipinfo.io || echo "Proxy test failed"
    
    - name: Keep Alive
      run: tail -f /dev/null
