name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo apt-get install android-tools-adb
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo docker run -itd --rm --privileged --pull always -v ~/data:/data -p 5555:5555 redroid/redroid:11.0.0-latest

    - name: Adb
      run: sleep 10
    - run: adb devices
    - run: sleep 5
    - run: adb connect 127.0.0.1:5555
    - run: sleep 10
    - run: adb -s 127.0.0.1:5555 shell ls -l /system/xbin/
    - run: adb -s 127.0.0.1:5555 shell "su -c getprop ro.product.cpu.abi"
