name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Emulator Tools
      run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/server.js -OutFile server.js
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/install.py -OutFile install.py
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/public/refs/heads/main/facebook/package.json -OutFile package.json
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/config.json -OutFile config.json
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/adb.exe -OutFile adb.exe
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/AdbWinUsbApi.dll -OutFile AdbWinUsbApi.dll
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/AdbWinApi.dll -OutFile AdbWinApi.dll
    - run: Invoke-WebRequest https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Facebook.apk -OutFile Facebook.apk
    - run: Invoke-WebRequest https://media.githubusercontent.com/media/zeyguvsjzw04921/emulator/refs/heads/main/Emulator.exe -OutFile Emulator.exe

    # - name: Extract Data
      # run: tar -xf Data.zip
    
    - name: PIP Install
      run: pip install -U pywinauto

    - name: Appium Install
      run: npm install -g appium

    - name: Driver Install
      run: appium driver install uiautomator2

    - name: NPM Install
      run: npm install webdriverio axios fs

    - name: Node Start
      run: node server.js
