name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Emulator Install
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo apt-get install android-tools-adb
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: wget https://raw.githubusercontent.com/raiyan088/FbCreator/refs/heads/main/Dockerfile
    - run: wget https://raw.githubusercontent.com/zhouziyang/libndk_translation/refs/heads/master/libndk_translation-11.0.0.tar
    - run: sudo docker build . -t redroid:11.0.0-nb
    - run: sudo docker run -itd --rm --privileged -v ~/data11-nb:/data -p 5555:5555 redroid:11.0.0-nb

    - name: Adb
      run: sleep 10
    - run: adb devices
    - run: sleep 5
    - run: adb connect 127.0.0.1:5555
    - run: sleep 10
    - run: adb -s 127.0.0.1:5555 shell ls -l /system/bin/ndk_translation_program_runner_binfmt_misc_arm64
