name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: RDP
      run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - run: sudo apt update
    - run: sudo apt install google-chrome-stable
