name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: sudo bash -c 'echo -e "[Unit]\nDescription=Dante SOCKS5 Proxy\nAfter=network.target\n\n[Service]\nType=simple\nExecStart=/usr/sbin/danted -f /etc/danted.conf\nUser=root\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/danted.service'
    - run: which systemctl
    
