name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: sudo apt install -y linux-modules-extra-`uname -r`
    - run: sudo apt-get install -y android-tools-adb
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo apt install -y linux-headers-generic
    - run: sudo apt-get install -y linux-headers-`uname -r`
    - run: docker run -itd --rm --privileged --pull always -v ~/data:/data -p 5555:5555 redroid/redroid:11.0.0-latest
    - run: sleep 60
    - run: adb connect localhost:5555
    - run: sleep 3
    - run: adb devices
    - run: sleep 10
    - run: adb devices
    - run: sleep 10
    - run: adb devices
    - run: sleep 10
    - run: adb devices
    - run: sleep 10
    - run: adb devices
    - run: sleep 10
    
