name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: sudo apt install linux-modules-extra-`uname -r`
    - run: sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
    - run: sudo apt install -y linux-headers-generic
    - run: sudo apt-get install linux-headers-`uname -r`
    - run: sudo modprobe ashmem_linux
