name: HTTP Proxy via TinyProxy
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tinyproxy wget unzip curl

    - name: Configure TinyProxy
      run: |
        sudo tee /etc/tinyproxy/tinyproxy.conf > /dev/null <<EOF
        Port 8888
        Listen 0.0.0.0
        Timeout 600
        LogLevel Info
        MaxClients 100
        Allow 0.0.0.0/0
        EOF

    - name: Start TinyProxy
      run: sudo systemctl restart tinyproxy

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip -o ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/
        rm ngrok-stable-linux-amd64.zip

    - name: Set Ngrok Authtoken
      run: ngrok config add-authtoken 2YMpPG6ws3Y1x5unwwSlUNVs3Wu_67JPAFd2MmxAo7cBVK7Lq

    - name: Start Ngrok TCP Tunnel
      run: nohup ngrok tcp 8888 > /tmp/ngrok.log 2>&1 &

    - name: Wait and Show Ngrok URL
      run: |
        sleep 8
        curl -s http://localhost:4040/api/tunnels > tunnels.json
        proxy_url=$(grep -oE 'tcp://[^"]+' tunnels.json)
        echo "HTTP Proxy URL: $proxy_url"

    - name: Keep Alive
      run: tail -f /dev/null
