name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: RDP
      run: sudo useradd -m user
    - run: sudo adduser user sudo
    - run: sudo echo 'user:root' | sudo chpasswd
    - run: sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
    - run: sudo apt update
    - run: sudo wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
    - run: sudo echo $'import os\nos.system("sudo dpkg --install chrome-remote-desktop_current_amd64.deb")' > remote.py
    - run: sudo python remote.py
    - run: sudo apt install --assume-yes --fix-broken
    - run: sudo apt install --assume-yes xfce4 desktop-base xfce4-terminal
    - run: sudo bash -c 'echo \"exec /etc/X11/Xsession /usr/bin/xfce4-session\" > /etc/chrome-remote-desktop-session'
    - run: sudo apt remove --assume-yes gnome-terminal
    - run: sudo apt install --assume-yes xscreensaver
    - run: sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - run: sudo echo $'import os\nos.system("sudo dpkg --install google-chrome-stable_current_amd64.deb")' > chrome.py
    - run: sudo python chrome.py
    - run: sudo apt install --assume-yes --fix-broken
    - run: sudo adduser user chrome-remote-desktop
    - run: sudo su - user -c 'DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AVG7fiQGL7l0AFnLGIO1SKOv1UYtywwi79yIAuSMOwPF6GInsSf0g-QsSU-X_efb5T-qTw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --pin=123456'
    - run: sleep 600
