name: HTTPS Proxy via Squid
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Squid Proxy
      run: |
        sudo apt update
        sudo apt install -y squid wget unzip curl

    - name: Configure Squid
      run: |
        sudo tee /etc/squid/squid.conf > /dev/null <<EOF
        http_port 3128
        acl all src 0.0.0.0/0
        http_access allow all
        access_log stdio:/dev/stdout
        EOF

    - name: Start Squid
      run: sudo systemctl restart squid

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip -o ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/
        rm ngrok-stable-linux-amd64.zip

    - name: Set Ngrok Authtoken
      run: ngrok config add-authtoken 2YMpPG6ws3Y1x5unwwSlUNVs3Wu_67JPAFd2MmxAo7cBVK7Lq

    - name: Start Ngrok TCP Tunnel
      run: nohup ngrok tcp 3128 > /tmp/ngrok.log 2>&1 &

    - name: Wait and Show Ngrok URL
      run: |
        sleep 8
        curl -s http://localhost:4040/api/tunnels > tunnels.json
        proxy_url=$(grep -oE 'tcp://[^"]+' tunnels.json)
        echo "HTTPS Proxy URL: $proxy_url"

    - name: Keep Alive
      run: tail -f /dev/null
